### ISSUE TITLE
Transición de estados al editar un bien

### ISSUE THREAD

**Issue by gisemartinez** [gisemartinez/ids#10]
Si un estado es En Uso no puede pasar directamente a Descarte, por ejemplo

**Comment by gisemartinez** [comment]
@nairolivera Necesitaría este esquema, así se puede hacer.

**Comment by nairolivera** [comment]
nunca que lei este mail. esta en el drive ya lo subo a git

2015-01-31 4:51 GMT-03:00 gisemartinez notifications@github.com:

**Comment by nairolivera** [comment]
perdon @gisemartinez no lo habìa visto. Te paso el esquema
![image](https://cloud.githubusercontent.com/assets/4562345/6101321/efc75782-b000-11e4-805e-f12b40bea5e3.png)
