### ISSUE TITLE
Al eliminarse una persona, debe aparecer un mensaje más claro

### ISSUE THREAD

**Issue by gisemartinez** [gisemartinez/ids#13]
Dejo la imagen. Había eliminado la persona de id:10 y apareció así ,en la parte de arriba de la pantalla
![image](https://cloud.githubusercontent.com/assets/1588592/5953436/ad03ef28-a768-11e4-88b2-c161128fdd0b.png)

**Comment by ayestaranguillermo** [comment]
Para el resto de las entidades esta comentado, pero supongo que habria que mostrar alguna clase de mensaje, solo que esos son muy feos.

**Comment by Manumental32** [comment]
Porque no prueban con esta librería de js? es muy facil de usar, compatible con cualquier cosa y viene con css tambien.
https://github.com/Manumental32/sweetalert

**Comment by nairolivera** [comment]
Por q les mandaba eso? Jaba

**Comment by ayestaranguillermo** [comment]
![image](https://cloud.githubusercontent.com/assets/7073737/6013905/0c516594-ab3a-11e4-9ced-d91b59d14f39.png)
