### ISSUE TITLE
Gráfico de bienes : todavía no le encontramos el lugar

### ISSUE THREAD

**Issue by gisemartinez** [gisemartinez/ids#15]
Habría que modificarlo?  Recordar que no le encontramos el lugar, así como a las "noticias"

**Comment by ayestaranguillermo** [comment]
![image](https://cloud.githubusercontent.com/assets/7073737/6085841/e503120a-ae1b-11e4-8151-8c9d2016fd18.png)

**Comment by ayestaranguillermo** [comment]
![image](https://cloud.githubusercontent.com/assets/7073737/6101822/a32ed82e-b009-11e4-96da-e3476dbcb402.png)

**Comment by nairolivera** [comment]
quedo bueno
