### ISSUE TITLE
Limitar cantidad de dígitos

### ISSUE THREAD

**Issue by gisemartinez** [gisemartinez/ids#2]
Limitar la cantidad de dígitos que tienen los campos al ser DNI, contraseña(si quisiéramos limitar, no se 4 letras, 4 números)

**Comment by ayestaranguillermo** [comment]
Para el DNI se puede llegar a hacer agregando los atributos min y max al input, con los valores 10000000 y 99999999 por tirar un ejemplo. El tema es que esto es html5, y tira un mensaje propio. De todas formas el mensaje es muy claro, y creo que podria ir bien, sin necesidad de modificar nada. A mi me lo tira en ingles, pero supongo que es porque mi pc esta configurada asi.

![untitled](https://cloud.githubusercontent.com/assets/7073737/5952245/c066d0a6-a751-11e4-8396-60e95f02cd70.png)

**Comment by gisemartinez** [comment]
Me gusta, creo que con Javascript también se podría hacer, preguntando si ese número es mayor a 99 millones

**Comment by ayestaranguillermo** [comment]
Esto es lo que buscamos me parece:

http://www.w3schools.com/tags/att_input_pattern.asp

**Comment by gisemartinez** [comment]
Si, creo que es lo más simple
