### ISSUE TITLE
Verificación Contraseña

### ISSUE THREAD

**Issue by rprada** [gisemartinez/ids#21]
Falta realizar la validación de la contraseña y que la compare con la escrita anteriormente para la correcta creación del usuario.

**Comment by ayestaranguillermo** [comment]
Mmm, parece que ya no esta andando :/ O soy yo?

![image](https://cloud.githubusercontent.com/assets/7073737/6914134/d5a9acb8-d75d-11e4-9dad-1a88dbc04892.png)

**Comment by ayestaranguillermo** [comment]
Se puede hacer respond dsd un servicio? Y si se puede, hara falta poner algo mas? Importar algo?

**Comment by gisemartinez** [comment]
Contame como lo hiciste aparecer al error, así lo reproduzco en casa y veo que está pasando.

**Comment by ayestaranguillermo** [comment]
Simplemente puse dos contraseñas distintas al crear un usuario :/ Ahora voy a probar algo

**Comment by ayestaranguillermo** [comment]
http://stackoverflow.com/questions/19132521/grails-render-view-from-service

**Comment by ayestaranguillermo** [comment]
Me parece q habria q mover ese manejo de errores y renders de vistas al controller otra vez. Probe de hacerlo y volvio a andar, solo que no logro mostrar el error.

**Comment by gisemartinez** [comment]
@ayestaranguillermo tenés razón. Tenés algo para subir ?Querés que lo siga viendo yo?Me pongo a hacer unas pruebitas y te digo si encontré como hacer.

**Comment by gisemartinez** [comment]
@ayestaranguillermo mirá esto : http://grails.github.io/grails-doc/3.0.x/guide/services.html#declarativeTransactions . Esa forma sería la más adecuada y aparte sería un buen momento para usar el concepto Try-Catch

**Comment by gisemartinez** [comment]
http://keithsgrailstips.blogspot.com.ar/2010/02/use-exceptions-to-control-validation.html
