### ISSUE TITLE
Busqueda

### ISSUE THREAD

**Issue by ayestaranguillermo** [gisemartinez/ids#29]

**Comment by ayestaranguillermo** [comment]
![image](https://cloud.githubusercontent.com/assets/7073737/6098341/33e5938a-afba-11e4-8d42-2465305a82d9.png)

**Comment by ayestaranguillermo** [comment]
![image](https://cloud.githubusercontent.com/assets/7073737/6101795/4166d196-b009-11e4-9d86-930ebd8c0722.png)

**Comment by gisemartinez** [comment]
En el servidor se puso así:
![image](https://cloud.githubusercontent.com/assets/1588592/6103062/6e3ae788-b01e-11e4-9572-58aea7f7f5ec.png)

**Comment by nairolivera** [comment]
En mi local también estaba así!  (Si, no logro dormirme :( )

**Comment by ayestaranguillermo** [comment]
Oka, me fijo

**Comment by gisemartinez** [comment]
Guille! Fijate si en la copia actual están todos tus cambios porque puede ser que se hayan pisado y por eso aparezcan así
