### ISSUE TITLE
Agregar información de cada Rol en el dropdown

### ISSUE THREAD

**Issue by gisemartinez** [gisemartinez/ids#4]
La opción "Permisos" actualmente no direcciona a ningún lugar. Se debe contar con esa información para poder crear la página donde se puedan mostrar.
![image](https://cloud.githubusercontent.com/assets/1588592/5945882/6d8f6276-a710-11e4-9e15-da0ed73d6c9f.png)

**Comment by nairolivera** [comment]
No me esta dejando reasignarlo, pero de este me ocupo yo ro!

**Comment by gisemartinez** [comment]
Mirá, con @ anda : @rprada

**Comment by nairolivera** [comment]
el texto de los permisos esta en el drive

**Comment by gisemartinez** [comment]
Solo falta mejorar la vista y cambiar los textos.

**Comment by ayestaranguillermo** [comment]
Estaba viendo si se podia asignar a mas de una persona :/

**Comment by ayestaranguillermo** [comment]
Despues me pongo a ver el tema de la vista.

**Comment by nairolivera** [comment]
Quizas habria que agregarle màs texto porque quedo medio pelado, pero a lo que habìamos puesto en el documento inicial no se me ocurrio agregarle mucho, sino parecìa màs un ayuda que permisos.

![image](https://cloud.githubusercontent.com/assets/4562345/6142184/1b3677b4-b190-11e4-8879-f35bda844195.png)
