### ISSUE TITLE
Rol debe estar visible en la barra de accesos

### ISSUE THREAD

**Issue by nairolivera** [gisemartinez/ids#46]

**Comment by ayestaranguillermo** [comment]
![image](https://cloud.githubusercontent.com/assets/7073737/7810787/93b7bdf0-037b-11e5-9734-3cfb3376f8bb.png)

**Comment by ayestaranguillermo** [comment]
![image](https://cloud.githubusercontent.com/assets/7073737/7810850/00f8762a-037c-11e5-8766-19e564252652.png)

**Comment by ayestaranguillermo** [comment]
![image](https://cloud.githubusercontent.com/assets/7073737/7831069/8670aba8-0429-11e5-9f91-02338da20a58.png)
