### ISSUE TITLE
Definir todos los roles necesarios

### ISSUE THREAD

**Issue by gisemartinez** [gisemartinez/ids#5]
Actualmente no están bien definidos los nombres. Cuando se definan ,se deben cargar en la base de datos de produccion, además de dar de alta usuarios pudiendo elegir dentro de esos roles

**Comment by gisemartinez** [comment]
Falta poner este comando en Producción. @nairolivera : cuando lo corras, podés cerrar éste issue 

INSERT INTO `role` (`id`, `version`, `authority`) VALUES
(3, 0, 'ROLE_SUPERVISOR');

**Comment by nairolivera** [comment]
Gi lo corro desde putty no?

**Comment by nairolivera** [comment]
ya fue cargado el rol, ademàs modifique el nombre a encargado, que es el correcto.
![image](https://cloud.githubusercontent.com/assets/4562345/6099128/6a1aba7e-afcf-11e4-9e50-1221dc6395dc.png)
