### ISSUE TITLE
Diferente forma de agregar entre Bienes y Personas

### ISSUE THREAD

**Issue by gisemartinez** [gisemartinez/ids#52]
![image](https://cloud.githubusercontent.com/assets/1588592/8022007/3f521d70-0c8e-11e5-86d5-0cc0814c2942.png)
![image](https://cloud.githubusercontent.com/assets/1588592/8022008/4b8411d4-0c8e-11e5-9d6e-d8bef02e1baf.png)
En una vista se agregan los vienes apretando el botón Rosa, pero en el otro sigue siendo igual. Va a quedar así?Podría haber confusiones.

**Comment by ayestaranguillermo** [comment]
No no, es solo porque me faltan subir esas vistas

**Comment by gisemartinez** [comment]
Ok! lo cierro entonces.
