### ISSUE TITLE
Agregar mensaje “No hay datos cargados”.

### ISSUE THREAD

**Issue by gisemartinez** [gisemartinez/ids#6]
Cuando los listados no tienen datos, colocarle un mensaje de “No hay datos cargados”.

**Comment by ayestaranguillermo** [comment]
![image](https://cloud.githubusercontent.com/assets/7073737/6013631/6130cebe-ab36-11e4-903b-2f55566c30ea.png)

**Comment by gisemartinez** [comment]
Genial. Me gusta la evidencia de que anda. Ya lo subiste? Cuando lo subas al repo agregá el numero de la incidencia. Ej. "Mensaje en listados vacíos. #6
