### ISSUE TITLE
Modificar pantalla de cuando se pierde el tiempo de sesión

### ISSUE THREAD

**Issue by gisemartinez** [gisemartinez/ids#7]
Se puede hacer con modals?

**Comment by ayestaranguillermo** [comment]
Que pantalla es?

**Comment by ayestaranguillermo** [comment]
O que controller lo maneja?

**Comment by gisemartinez** [comment]
Es la del controller Auth . El path es: ids\target\work\plugins\spring-security-core-2.0-RC4\grails-app\controllers\grails\plugin\springsecurity y se llama LoginController. El .gsp al que va cuando se vence la sesión es el auth, (es el pedacito que se muestra en el main) y está en el path: ids\target\work\plugins\spring-security-core-2.0-RC4\grails-app\views\login .

**Comment by ayestaranguillermo** [comment]
Oka. Cada cuanto se pierde la sesion?

**Comment by gisemartinez** [comment]
Cada media hora creo. Si te colgás mirando la novela, se te va la sesión. Ojo, puse lo de modal pero era más una nota mental que otra cosa.
